---
- hosts: development
  remote_user: root
  
  vars:
    mysql_root_password: bluetea
    packages:
      - git
      - htop
      - atop
      - python-mysqldb
      - libcap-dev
      - git
      - libicu-dev
      - libssl-dev
      - zip
      - unzip
      - acl
    usergroups:
      - admins
      - developers
      - users
    users:
      - { name: administrator, home: /home/administrator, group: 'admins', secundary_groups: 'developers,users' }

  pre_tasks:
    - name: PRE TASK | Add python-apt package
      apt: pkg=python-apt state=present

  roles:
    - common
    - apache2
    - mysql
    - supervisor
    - rabbitmq
    - mongodb
    - npm
    - pecl
    - samba
    - phpmyadmin
    - oh-my-zsh
