---
- hosts: development
  remote_user: root
  
  vars:
    mysql_root_password: bluetea
    packages:
      - git
      - htop
      - atop
      - python-mysqldb
      - libcap-dev
      - git
      - libicu-dev
      - libssl-dev
      - zip
      - unzip
    usergroups:
      - admins
      - developers
      - users
    users:
      - { name: pim, home: /home/pim, group: 'admins,developers,users' , key: "{{ lookup('file', 'sshkeys/pim.pub') }}" }
      - { name: bert, home: /home/bert, group: 'admins,developers,users' , key: "{{ lookup('file', 'sshkeys/bert.pub') }}" }

  pre_tasks:
    - name: PRE TASK | Add python-apt package
      apt: pkg=python-apt state=present

  roles:
    - common
    - apache2
    - mysql
    - supervisor
    - rabbitmq
    - mongodb
    - npm
    - pecl
    - samba
    - phpmyadmin
