---
- name: APT | Install Apache
  apt: pkg=apache2 state=present

- name: APT | Install PHP5
  apt: pkg={{ item }} state=present
  with_items: apache2_packages

- name: Apache2 module | Enable rewrite
  apache2_module: name={{ item }} state=present
  with_items: apache2_modules

- name: Template | Configure virtual hosts
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-enabled/vhosts

- name: Service | Start apache2
  service: name=apache2 state=started
