---
- name: Debconf | dbconfig-install
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: Debconf | app-password-confirm
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql_root_password}}' vtype='password'

- name: Debconf | mysql/admin-pass
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_root_password}}' vtype='password'

- name: Debconf | mysql/app-pass
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{mysql_root_password}}' vtype='password'

- name: Debconfig | reconfigure-webserver
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: APT | Install phpmyadmin
  apt: pkg=phpmyadmin state=present

- name: File | Symlink phpmyadmin directory to www directory
  file: path=/var/www/html/phpmyadmin src=/usr/share/phpmyadmin state=link
