- name: Debconf | root_password
  debconf: name=mysql-server question='mysql-server/root_password' value={{ mysql_root_password }} vtype=password

- name: Debconf | root_password_again
  debconf: name=mysql-server question='mysql-server/root_password_again' value={{ mysql_root_password }} vtype=password

- name: APT | mysql-server
  apt: pkg=mysql-server state=present

- name: Service | Start mysql-server
  action: service name=mysql state=started

- name: Mysql_user | update mysql root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: Template | copy .my.cnf file with root password credentials
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Mysql_user | delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" state="absent"
  ignore_errors: true

- name: Mysql_user | delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
  ignore_errors: true

- name: Mysql_db | remove the MySQL test database
  action: mysql_db db=test state=absent
  ignore_errors: true
