- name: PECL | Test for previous "{{ package }}" install
  shell:  pecl list | grep -i {{ package }}
  register: php_package_exists
  ignore_errors: yes

- name: PECL | Install {{ package }}-{{ version }}
  shell: yes '' | pecl install {{ package }}-{{ version }}
  when: php_package_exists|failed

- name: PECL | Set {{ package }} config for Apache2 (Ubuntu == 12.04)
  template:
    src=pecl/{{ package }}.ini.j2
    dest=/etc/php5/apache2/conf.d/{{ package }}.ini
    owner=root group=root mode=0644
  when: ansible_lsb.release == "12.04"
  notify: restart apache2

- name: PECL | Set {{ package }} config for CLI (Ubuntu == 12.04)
  template:
    src=pecl/{{ package }}.ini.j2
    dest=/etc/php5/cli/conf.d/{{ package }}.ini
    owner=root group=root mode=0644
  when: ansible_lsb.release == "12.04"

- name: PECL | Set {{ package }} config (Ubuntu > 12.04)
  template:
    src=pecl/{{ package }}.ini.j2
    dest=/etc/php5/mods-available/{{ package }}.ini
    owner=root group=root mode=0644
  when: ansible_lsb.release != "12.04"

- name: PECL | Set symbolic link to {{ package }} config for Apache2 (Ubuntu > 12.04)
  file:
    src=/etc/php5/mods-available/{{ package }}.ini
    dest=/etc/php5/apache2/conf.d/20-{{ package }}.ini
    owner=root group=root state=link
  when: ansible_lsb.release != "12.04"
  notify: restart apache2

- name: PECL | Set symbolic link to {{ package }} config for CLI (Ubuntu > 12.04)
  file:
    src=/etc/php5/mods-available/{{ package }}.ini
    dest=/etc/php5/cli/conf.d/20-{{ package }}.ini
    owner=root group=root state=link
  when: ansible_lsb.release != "12.04"
