---
- name: Group | Create
  group: name={{ item }} system=yes state=present
  with_items: usergroups

- name: User | Create
  user: name={{ item.name }} home={{ item.home }} group={{ item.group }} groups={{ item.secundary_groups }} state=present
  with_items: users
