---
- name: create groups
  group: name={{ item }} system=yes state=present
  with_items: usergroups

- name: create users
  user: name={{ item.name }} home={{ item.home }} groups={{ item.group }} state=present
  with_items: users

- name: add ssh keys to the created users
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: users
