---
- name: Group | Create
  group: name={{ item }} system=yes state=present
  with_items: usergroups

- name: User | Create
  user: name={{ item.name }} home={{ item.home }} group={{ item.group }} groups={{ item.secundary_groups }} state=present
  with_items: users

- name: Authorized Key | Add ssh keys to the created users
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: users
