---
- name: Make sure Apache2 service is started
  service: name=apache2 state=started

- name: Make sure mysql server service is started
  service: name=mysql state=started

- name: Make sure RabbitMQ server service is started
  service: name=rabbitmq-server state=started

- name: Make sure supervisord service is started
  service: name=supervisor state=started
